### ISSUE TITLE
Orphan and included concepts are not displayed for some data source

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#100]
Related to https://github.com/OHDSI/CohortDiagnostics/issues/77

There is no orphan (source) concepts displayed
![image](https://user-images.githubusercontent.com/13936600/87874061-b0656800-c994-11ea-9866-33a69d876280.png)

But, there are orphan (source) concepts for the same concept set 
![image](https://user-images.githubusercontent.com/13936600/87874069-c3783800-c994-11ea-8889-4079fdf66ff5.png)

This is bug and is causing confusion. For the same concept-set, selecting one database makes us think there is no orphan-codes. Choosing another, shows that there are orphan codes.

Background: Orphan code computation was an expensive process. So, to gain efficiency on orphan code checking and included events tabs, we only processed unique conceptsets when the same cohort definition was processed across multiple databases. The negative consequence is that in the UI, there is only one database that ‘holds’ the results for the conceptset. All other databases for the same cohort which may use that same conceptset may show nothing (as above). 

Potential solution:   can we make the UI display the results for all conceptsets that are included in a given cohort, even if it wasn’t computed for a database?

**Comment by cgreich** [comment]
@gowthamrao: How do you calculate them anyway? And is that something that we could pre-compute?

**Comment by schuemie** [comment]
Orphan concepts are (source) concepts that likely should be included in a concept set, but aren't, often because of vocabulary issues. This is a rough outline of the process:

<ul>
<li>Given a concept set expression, find all included concepts.
<li>Find all names of those concepts, including synonyms, and the names of source concepts that map to them.</li>
<li>Search for concepts (standard and source) that contain any of those names as substring.</li>
<li>Filter those concepts to those that are not in the original set of concepts (i.e. orphans).</li>
<li>Restrict the set of orphan concepts to those that appear in the CDM database as either source concept or standard concept.</li>
</ul>

Given that last step, the orphan codes will be different for different databases. @gowthamrao : why is that a bug? The reason we do this last step is because there are *always* orphan concepts, but we only care about the ones that are actually used in the data.

@cgreich : yes, most of this can in fact be pre-computed (assuming the orphan codes aren't in a local source-to-concept-map). I think Patrick was working on that.

**Comment by gowthamrao** [comment]
Also related to
https://github.com/OHDSI/CohortDiagnostics/issues/56
