### ISSUE TITLE
incremental = incremental?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#1031]
https://github.com/OHDSI/CohortDiagnostics/blob/main/R/ConceptSets.R#L965

Was this supposed to be incremental = incremental?

Snowflake was bombing here.

Tagging @drTtrousers

**Comment by DrTTrousers** [comment]
Some further detail, this issue was specifically found in one of the older versions and fixing the incremental variable corrected the bomb, but - Don't know why it caused it on snowflake (not redshift with exactly the same setup)

Also, v3.x Diagnostics does fix this from happening because....
``` r
writeToCsv.default <- function(data, fileName, incremental = FALSE, ...) {
  colnames(data) <- SqlRender::camelCaseToSnakeCase(colnames(data))
  if (incremental) {
    params <- list(...)
    if (length(params) > 0) {
      names(params) <- SqlRender::camelCaseToSnakeCase(names(params))
    }
```
This check to ensure that there is actually content in the list object has been added. However, the same effect could be provided by removing the forced incremental.

**Comment by azimov** [comment]
Please post a log file/error report of the thrown error.

**Comment by azimov** [comment]
closed due to inactivity
