### ISSUE TITLE
Do we need both subjectId and entries in Cohort Counts?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#110]
In situations where subjectId = entries, it is distracting to have both. In most cases, we will have subjectIds = entries, - in those cases, we only need to see subjectId

Create option to have either only subjectids, or only entries, or both. Make default subjectids.

**Comment by pbr6cornell** [comment]
I think having an option is a nice to have feature, but I would recommend that showing both is the preferred default. Reason being is that confirming that the number of events equals the number of subjects is, itself, a valuable diagnostic, and when there can be multiple events, seeing how many events relative to distinct persons is also informative.

**Comment by schuemie** [comment]
Yes, I can confirm that I have been surprised myself by discrepancies between the two counts, when I was convinced beforehand that they would be the same. (which in hindsight was caused by the fact that people can have multiple observation periods). I would also prefer the default to be to show them both.

**Comment by gowthamrao** [comment]
Thanks for the feedback, maybe it would be useful for the display to check when they are different - and may change color/font etc
