### ISSUE TITLE
Show details of concept set expression

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#115]
- exported cohort object has cohort expressions, which in turn has all the concept set expressions
- concept set expressions are used in included (source) concepts and orphan (source) concepts
- it would be useful to display the concept set expression as a dataframe in the shiny application

Steps:
- get the cohorts json expression
- extract the concept set expression from cohort
- make a print friendly display

> conceptTbl <-
  convertConceptSetDefinitionToTable(conceptSetDefinition)
names(conceptTbl) <-
  SqlRender::camelCaseToTitleCase(names(conceptTbl))

**Comment by pbr6cornell** [comment]
In CohortDiagnostics, the primary evaluation is against conceptsets that make up the entry events, because here we can evaluate included concepts, orphan concepts, and index events.    Included and orphan concepts can be 'design diagnostics' that are evaluated against OHDSI ConceptPrevalence, while index event is a 'data diagnostics' that needs to be run against patient-level data within a given source.

For display purposes, we want to find a way to communicate the content of a cohort definition as fully as possible.   That includes the name and Logic Description provided by the user.  ATLAS also provides a human-readable description, that this can be used but doesn't replace the need for the user to try to express their intent (to be verified by reviewing the definition and ATLAS-generated description).   In practice, many definitions have minimal cohort logic but have tremendous effort put into the conceptset expression construction, so particular focus should be around how to show the conceptset content as effectively as posisble.

Whenever we show a conceptset expression, we have to show 'included concepts', which is the full enumerated list of concepts that are derived from the conceptset expression.   We also have to show 'included source codes', which is the full list of source concepts that map up into the 'included concepts'.   Both of these can benefit by having OHDSI ConceptPrevlaence statistics to show the relative frequency and spread of use of each concept across the community.    Note, all conceptset expressions in ATLAS do expose the 'conceptset expression', 'included concepts' and 'included conceptsets', so potentially re-use of that UI component could be made possible.

**Comment by gowthamrao** [comment]
This is now implemented. Logic for concept sets in new package ConceptSetDiagnostics http://github.com/ohdsi/conceptSetDiagnostics
