### ISSUE TITLE
Option to read data from database inaddition to premerged file and csv

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#155]
In R shiny global.R file we should attempt to support multiple inputs
- csv (already available)
- .RData (already available)

We need to add
- database support with pooling similar to https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/pull/67

@anthonysena

**Comment by azimov** [comment]
To add to this issue, and capture much of what we have been discussing internally, it would be good if the output of cohort diagnostics could be imported in to a common sql database backend to allow the application to scale to many thousands of cohorts.

I think this will require a fairly significant rewrite of how the cohort diagnostics app loads the data as at the moment the RData file is loaded and all data frames are accessed directly. If we are to support a database backend I don't think it would be ideal to load data in this manner and, instead, it should be loaded in reactive blocks with a common interface for all 3 data backends.

For example:
```
output$cohortDescriptionTable <- DT::renderDataTable({
    data <- dataBackend$getCohortDescriptionTable()  %>% 
      dplyr::mutate(atlasId = as.integer(.data$atlasId)) ...
     # Do the rest of the data manipulation
    return(dataTable)
  })

```
Where dataBackend is an object that either handles csv files, RData or an RDBMS.

How to design the common data backend should be just about pulling the data - if too much manipulation is done in this object we will have to implement that 3 times. Where everything is in dataframes this is fine but, for example, doing a group_by in the database would likely be more efficient than doing it in R and it would be best practice to avoid anything like:

```
if(usingADatabase) {
   result <- queryDb("SELECT DISTINCT ....")
} else {
   result <- unique(data)
}
```

I think we made the design decision to only support postgres for this export purpose. We could use dbplyr instead of database connector as this allows use of dplyr calls that automatically convert queries to sql and return response. Alternatively there would be either a performance or code replication overhead to resolve this.

**Comment by gowthamrao** [comment]
@anthonysena as we design a shared results data model, we need to standardize the input from (and probably output of) phevaluator
Related to https://github.com/OHDSI/CohortDiagnostics/issues/132

**Comment by gowthamrao** [comment]
Related to https://github.com/OHDSI/CohortDiagnostics/issues/125 as we may want to capture this information in the common results data model

**Comment by gowthamrao** [comment]
@azimov as we design the solution please consider this issue https://github.com/OHDSI/CohortDiagnostics/issues/38

**Comment by gowthamrao** [comment]
Added in version 2
