### ISSUE TITLE
Allow for concept_count to be input parameter, rather than calculated off database

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#16]
The Orphan concept count would be more powerful if it were run off a composite summary of concepts across a data network (e.g. JNJ network summary of ACHILLES or the ongoing OHDSI concept prevalence study).   Doing so would mean you'd only have to run orphan check once, fix your conceptset once, and be done, rather than iteratively updating and checking for each database.  Not everyone has a composite summary, but if they do and it were formatted in some appropriate manner (e.g. a table with columns:  CONCEPT_ID, RECORD_COUNT), and it contained both 'source_concept_id' and 'standard' concept_id, then it would seem logical to pass that in and use it.

**Comment by schuemie** [comment]
Agreed. This could also work for the 'included (source) concepts' diagnostic, assuming we'd have the mapping information available.

This is actually already somewhat supported, since you'd just need to not use [this code](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/CreateConceptCountTable.sql) to populate the counts table. But the question is more how this would work mechanically. Would someone come with a CSV file? Would there be a table already on the server, and if so, would there be one table per database? Do we need to allow for different columns names other than the current `concept_id` and `concept_count` columns?
