### ISSUE TITLE
Ideas for Diagnostics for Cohort Exist

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#298]
We would like to build diagnostics for cohort exit, such as:
1. what was the visit context at the time of exit
2. What were the events at the time of exit
3. What was the reason (rule) that lead to the exit

**Comment by gowthamrao** [comment]
4. Distribution of observation person days after cohort end date

**Comment by gowthamrao** [comment]
Technical solution:
An easy solution to generate characteristics on cohort_end_date is to create a new cohort on the fly, where cohort_end_date becomes the cohort_start_date. Then run feature extraction, cohort relationship etc on the new cohort table

**Comment by gowthamrao** [comment]
We are increasingly defining reasons why a person may exit a cohort. e.g. if platelet levels return back to normal for persons with thrombocytopenia.

We would really benefit from a new diagnosis that perform index event like breakdown on exit event. 

Can we characterize the cohort based on cohort end date?

**Comment by azimov** [comment]
@gowthamrao please specify some ideas on how we could define exit diagnostics for general cohorts. This could be extremely useful but I'm not sure how we can implement anything in the general case as exit can just stem from the cohort definition (e.g. its a single day). It could also be due to some immortal time in the definition (e.g. only patients that have surgery after 30 days).

**Comment by azimov** [comment]
Duplicates #1035 so closing as this has more formal specifics
