### ISSUE TITLE
Replace pre-merged file with Sqlite DB/Andromeda file

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortDiagnostics#539]
After discussions with @anthonysena, we noted that an implementation caveat with CohortDiagnostics and LSC is that there is a use of both a postgres database implementation and use of PreMerged files for use in the shiny apps. Ideally, we would like a single data storage model that works whether the data is big or small.

Is there a good reason why the study organiser can't convert the CSV files to an Sqlite database? This would unify the data model which would aid in developing more modular applications in the future. We could also resolve the postgres only functionality that is included in the Shiny apps to support hosting on any DatabaseConnector/SqlRender compatible platforms (though there may be some caveats for storage of json strings/cohort definitions in platforms like redshift).

**Comment by gowthamrao** [comment]
I think @leeevans is interested in this idea https://github.com/OHDSI/CohortDiagnostics/issues/317

We dont use sqlite because its not designed for concurrent queries. We want the db that hosting the result set to be able to support multiple connections - including SQL based queries from users. Shiny app is not the only user of the connection

**Comment by gowthamrao** [comment]
@azimov as long as we can support the SQL translations, we can achieve this

**Comment by gowthamrao** [comment]
If we decide to pursue this, i recommend we work on it - after next release

**Comment by leeevans** [comment]
@azimov I really like this idea. I began working on implementing the premerge file functionality into a standard function in the ohdsisharing package. I paused that activity to work on the Symposium infrastructure. I'm starting to work on that again now. We can create a mergeToSqlite function in the ohdsisharing package to load/merge the csv files into a single sqlite database file.

@gowthamrao made a good point that it is useful to retain the use of csv files at local sites because they can be easily opened and reviewed in simple tools like Excel, so this sqlite file would be created in addition to the csv files generated by the study.

**Comment by azimov** [comment]
@leeevans Agreed, the data storage at sites/from the base analysis should still be in CSV formats so we don't need to touch this.

I see there being a few steps to this:
1) making the sqlite DB from the CSV files in ohdsi sharing
2) Modifying the shiny requests to use only DatabaseConnector calls and taking out any postgres specific queries (if there are any?)
3) Optimising the shiny app load (the premerged file will probably load the app faster)

@gowthamrao this also relates to issue #434 as we will not need to expose the model to the pre-merged file.

**Comment by gowthamrao** [comment]
> making the sqlite DB from the CSV files in ohdsi sharing

What do you think of the primary output being sqlite - and then a secondary step of converting it to CSV.. i.e. the study package outputs sqlite and takes as input sqlite (where applicable). That way we can avoid the need guessing data types while reading in csv

>  we will not need to expose the model to the pre-merged file

@schuemie has introduced a construct called 'dataSource' - i.e. for any function that extracts data from the results data model, you pass in a parameter to the function called dataSource. It maybe a remote db connection or a connection to file system - but all that information is in the dataSource object.
