### ISSUE TITLE
checkFixColumnNames()

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#702]
Some data partners have additional columns added to the CDM as metadata.  Adding columns to the CDM does not break CDM conventions.

This causes an issue here:
```
2021-12-03 17:28:34	[Main thread]	FATAL	CohortDiagnostics	checkFixColumnNames	Error in checkFixColumnNames(table = newData, tableName = tableName, zipFileName = zipFiles$zipFile[i],  :    Column names of table concept in zip file C:/R EHDEN Packages/Covid19SubjectsAesiIncidenceRate/Output/cohortDiagnostics/Results_DP.zip do not match specifications. - Observed columns: concept_class_id, concept_code, concept_id, concept_name, domain_id, DP_dataloadrunid, DP_validfrom, invalid_reason, standard_concept, valid_end_date, valid_start_date, vocabulary_id - Expected columns: concept_class_id, concept_code, concept_id, concept_name, domain_id, invalid_reason, standard_concept, valid_end_date, valid_start_date, vocabulary_id 
```

I could ask the DP to remove the extra columns, however I wonder if the extra columns could be excluded upstream or this check doesn't bomb when there are extra columns.

**Comment by gowthamrao** [comment]
It appears there are columns in data that are not part of the CDM. in this case, this is the concept table.
Cohort Diagnostics makes a copy of the concept table (and other vocabulary tables) at the last step here

https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/R/ConceptIds.R#L66-L84

In these steps, we filter the vocabulary tables to the conceptIds in the cohort definition and make a copy using `"SELECT * FROM `

In this site, there were additional fields - so those were pulled. This is not a bug ofcourse, its an expected behavior.

The question is should we specificy columns in SELECT statement (e.g. `SELECT concept_id, concept_name` etc). The answer is NO - because, what if a site decides to not conform to the vocabulary table DDL and remove column (e.g. remove source_concept_code). In that case, the SQL would cause an error.

So i dont think we need to do any changes to CD code

**Comment by gowthamrao** [comment]
Next is the premerge

https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/R/Shiny.R#L186

We could make this a little less strict
https://github.com/OHDSI/CohortDiagnostics/blob/93e8915b504318300c68a565945dd17807a88567/R/ResultsDataModel.R#L61-L99

@azimov what do you think?

**Comment by azimov** [comment]
I see no reason why we can't set it so that there are a set of essential column names, this could just be done with
```
checkmate::checkNames(observeredNames, must.include = expectedNames)
```

However, I'm not sure what happens with the preMerge code when its merging the files. It would be pretty striaghtforward to filter the data so it's only using the expected columns though.

**Comment by azimov** [comment]
I have added a test to allow extra columns in the database which doesn't create issues in the develop branch, as far as I can tell. We can't modify CDM tables in tests (outside of the sqlite tests) so some user testing may be needed to confirm this bug has gone away in v3.0.0
