### ISSUE TITLE
Add tests for different database platforms

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#704]
There are currently no automated tests whether CohortDiagnostics runs on the different database platforms. These should be added, using the database platforms in the OHDSI CI testing environment (SQL Server, PostgreSQL, Oracle, RedShift, Bricks). We might be able to add BigQuery as well. 

These tests would need to be fairly light, so for example the number of cohorts need to be kept low (I think everything can be tested with 2 cohorts)

**Comment by azimov** [comment]
I think this is useful and should probably be included before the next release as this sort of integration testing will help minimise errors when studies are deployed.

I made a new PR (see #706) but I don't have a BigQuery or Redshift Test CDM to apply this. 

One further note note is that the tests on the CDMs can take much longer than Eunomia, possibly due to the synpuf cdm size. It maybe be good to have Eunomia sized CDMs on the servers.

**Comment by gowthamrao** [comment]
I think we should just Eunomia for testing - that way we can also test the expected output. Eunomia also ships with a lighter version of the vocabulary that makes everything faster IMO

**Comment by azimov** [comment]
The tests in the PR are set up to only run if the configuration settings are there for a given db, otherwise only sqlite will run. This means that any user can run the tests.

We could, though, have a fast testing for PRs and then only implement the full suite of database integrations upon merge to develop/master branches.

**Comment by azimov** [comment]
Tests now exist for all database platforms however there are few caveats:

* even though only 3 cohort ids are tested on the different platforms, they are extremely slow. This is likely because of the size of the vocabularies. @schuemie @leeevans my proposed solution to this would be to create Eunomia CDMs on all the test platforms; these would be minimal vocabularies and allow consistent testing across all the data platforms.

* The redshift tests are currently not running because CohortDiagnostics needs to be able to create tables, this wasn't possible on the schema's set up when i last checked. When this is fixed [these lines ](https://github.com/OHDSI/CohortDiagnostics/blob/develop/.github/workflows/R_CMD_check_Hades.yml#L47-L51)can be uncommented from the actions configuration.

**Comment by gowthamrao** [comment]
We are now doing tests in sql_server, postgres, sqlite, oracle
