### ISSUE TITLE
Integrate results when cohort id's dont match but cohort json match

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#770]
Use case:

- a site cherry picked cohorts used in a study and imported to their atlas
- created a new study package 
- executed the study and shared results
- we would like to integrate the results to main study package

Problems:
- the cohort id's do not match, because usually the cohort id are the same as atlas id. 

Solution:
- If we really want to integrate the results then
-	Check and confirm that cohort json from donating atlas matches receiving cohort jsons in study package
-	If cohort json match, check if the corresponding cohort id’s match.
-	If they don’t match - we need a way to override the donating atlas cohort id so that it matches the cohort id in the study package

**Comment by azimov** [comment]
@chrisknoll on the atlas side is there a standard hashing approach? I think having a global solution for cohorts is a good idea. But tracking changes between a cohort in Cohort DIagnostics is more complicated than it first sounds as there is no history stored within a cohort. If the hash implementation is not consistent then 2 identical cohorts could be different because line endings are change, whitespace changes etc.

**Comment by gowthamrao** [comment]
@chrisknoll any insight on this would be great! i ran into another scenario this week, where a collaborator imported the cohort definitions, thereby reassigning the cohort ids, executing the results and contributing.

Its tedious to manually compare cohorts - and a process to some how compare, deduplicate, reassign id would make it very useful.

**Comment by azimov** [comment]
I feel this is out of scope for the project. A user should specify a cohort definition set and id associated with a cohort it is niether straightforward or desirable to infer an ID from the cohort definitions
