### ISSUE TITLE
makeDataExportable function reports violation with index event breakdown

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#871]
Observed

```
Stack trace:
8: stop(" - duplicates found in primary key for table ", tableName, ". The primary keys are: ", paste0(primaryKeyInDataModel, collapse = ", "))
7: makeDataExportable(x = data, tableName = "index_event_breakdown", minCellCount = minCellCount, databaseId = databaseId)
```

Reason  - unknown

**Comment by azimov** [comment]
In version 2.2 the code did not include checks on the primary key fields. This means this bug is historical and is likely due to the calculation of index event breakdowns.

Note that the [query that unions](https://github.com/OHDSI/CohortDiagnostics/blob/5567b89bd29ae84d9719e0805b1f3ee8b516dd9c/inst/sql/sql_server/CohortEntryBreakdown.sql#L37) will not produce distinct elements if the counts are different.

**Comment by gowthamrao** [comment]
Yup - the original SQL seems to have a BUG as discussed here https://github.com/OHDSI/CohortDiagnostics/pull/894#issuecomment-1206768366
