### ISSUE TITLE
Develop branch - metadata view

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#878]
Current implementation requires user to do double selection -- select the databaseId from drop down, and select the row of the database in the table

![image](https://user-images.githubusercontent.com/13936600/182705448-e0a222ba-001a-4e64-9c53-ce25779fdf2f.png)

Ideally - user should do only one selection.

If drop down - then there should not be a need to row select table
If row select - then there should not be cohort drop down, the table should show all database. And if user does row select - details should be shown

**Comment by azimov** [comment]
This is because multiple runs was breaking the table before. the users can now select the reactable to see the results of each run (e.g. if incremental mode is used). As this is only for us to debug the application I don't see this as a priority, the data model for parsing this data is also very confusing so the change is not trivial.

**Comment by gowthamrao** [comment]
I see - that makes sense. I forgot about the multiple log entries per database with different time stamps - because of incremental mode.

So your design makes sense.
