### ISSUE TITLE
Cohort Definition tab:  Error in Subejcts/Count column rendering

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#922]
Steps:   Go to Anaphylaxis cohort, select Anaphylaxis conceptset, select Mapped tab:

![image](https://user-images.githubusercontent.com/731930/191116425-ee43513a-cfca-4a36-829c-5868d0017bbb.png)

Sort data on 'Subjects' column, and count disappear but blue histogram background bars persist:

![image](https://user-images.githubusercontent.com/731930/191116545-c05c7368-185f-4f2a-bd28-da7b0dfc2211.png)

Note, the first time I went to Mapped, these columns Subjects/Counts appeared   (but did not appear on the Resolved tab).   But, when I go back to 'Resolved' tab, the columns appear but they are empty.

![image](https://user-images.githubusercontent.com/731930/191116737-f1fcfd59-305d-4c83-a290-c15f12ca5af1.png)

If these columns are to appear, then they should be populated and should be sortable (presumably with the blue histogram background working correctly).

**Comment by gowthamrao** [comment]
Adding additional comments:

1. We have used subjects/persons, records/count interchangeably sometimes in the same page. I recommend we consistently use persons (instead of subjects), and records (instead of count) consistently across the app. And we describe them in the info button.

2. Could we check if the mapped concepts query function - its taking a long time for querying a simple pre-computed table

**Comment by azimov** [comment]
@pbr6cornell I have replaced the histogram function with a color gradient until I can figure out a javascript method that works with sortable columns - the method of using a background image doesn't work very well and may take a while to find a solution.
