### ISSUE TITLE
Cohort Counts tab:  suggested enhancements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#929]
1.  Table of person and record counts contain integers, but are formatted as decimal.   Suggestion:   format as int.
![image](https://user-images.githubusercontent.com/731930/191135682-68311873-9411-41fb-8e0c-b6083bd1c1d8.png)

2.  It is challenging to read this table, because there are two columns Cohort Id and Cohort, which provide non-readable information, and one has to 'lookup' the mapping to the cohort name in the table above the display.     It would much more desirable to list the cohort name directly in the table.

3.  "download as csv' only exports the filtered records in the table.    And the downloaded file only contains the cohortId and cohort columns NOT the cohortname, which makes the resulting file effectively unusable because the reference to the semantics of the ID is lost.   Suggestion:  include the cohortname in the export.

**Comment by gowthamrao** [comment]
Adding cohort name makes it more readable. We did the look up before because we couldnt do it with 'DT' package. We are now using 'reactable' that has many options:

Names are long and take a lot of screen space, so we may need to be able to
- dynamically change the width of the name
- hide/show column
- add text wrap so that text is displayed multi line if needed
- add hover over cell - tool tip shows full text of the cell

I am currently using full text name as follows, but have only enabled dynamic width change.

![image](https://user-images.githubusercontent.com/13936600/191268671-b921c64b-0e8c-40d6-a7c4-f24d1326482d.png)
