### ISSUE TITLE
Inclusion rule statistics - bug

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#939]
Inclusion rule statistics is not displayed when data exists. Erroneously shows that there is no data. 

![image](https://user-images.githubusercontent.com/13936600/191383821-1328fd34-93b5-4ca6-8322-aae16162e089.png)

Also inclusion rule menu is not rendered, but we may considered to remove it - as discussed here https://github.com/OHDSI/CohortDiagnostics/issues/938

**Comment by azimov** [comment]
Bug not confirmed in a schema with inclusion rules table populated:

<img width="1206" alt="Screenshot 2022-09-27 at 12 51 47 PM" src="https://user-images.githubusercontent.com/180659/192623373-e19cc839-8b7f-44ee-8919-e847b3bd88e6.png">

 - are you sure the table is populated. This must be another issue elsewhere in the pipeline and there are few things that could have gone wrong (maybe user error or a bug):

* Inclusion rules selected in analysis (in this case, obviously not a bug)
* Inclusion rules not executed/tables not populated when cohorts generated (config error or cohortGenerator issue)
* Inclusion rules not pulled in correctly from cohort generator
* Inclusion rules table not uploaded in data upload to database

Please confirm the version you used to generate the analysis. The first thing I would check would be the inclusion rules csv files for each database - if they are present and have values then they aren't being uploaded.

If they are not present it may be that the stats aren't generated by cohort generator because of a bug or user error.

If we can confirm the stats tables are being populated then the tables may not be passed to `executeDiagnostics` correctly.

**Comment by gowthamrao** [comment]
Well - i just checked again

this is expected
![image](https://user-images.githubusercontent.com/13936600/192660191-a16f9110-e0f5-4d66-8dd7-0d8422b77484.png)



this is observed
![image](https://user-images.githubusercontent.com/13936600/192660224-0b3836b9-5920-4fa3-8d13-261c579264f2.png)

**Comment by gowthamrao** [comment]
Yup - the stats table are populated

![image](https://user-images.githubusercontent.com/13936600/192660960-9675907d-17b2-4e0a-9343-d4f27161d289.png)

**Comment by gowthamrao** [comment]
resolved by https://github.com/OHDSI/CohortDiagnostics/commit/df4a73cd6a76c0f1e37fceca71650e861aba4784#diff-354b0d7194e99d757c74bd0da331f460c5ebf4197bd02ea33e8c7b8873927853

**Comment by gowthamrao** [comment]
in this example, the inclusion_rule_stats did not have any data, but these tables had data https://github.com/OHDSI/CohortDiagnostics/blob/befe0eb0e488fa8a4d308fed861cb03c64b67294/inst/sql/sql_server/CreateResultsDataModel.sql#L129-L174

we dont know the reason why this happened. Irrespective, we dont need inclusion_rule_stats tables anymore because we have all the inclusion rule table generated via circe .
