### ISSUE TITLE
Cohort Characterization:  age reported as %

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#949]
![image](https://user-images.githubusercontent.com/731930/192121699-b0877436-7001-4132-aa9c-1a47dae28bbe.png)

Top reproduce: Select cohort, database, time invariant window,  demographicsAge. domain: demographics

Age in years is a decimal value,  but shouldn't be formatted as a percentage. 

Note, this is tricky since most features are %.    I think it may be here because its a continuous variable, but filtering to 'proportion' didn't remove it from list?

**Comment by azimov** [comment]
So the percentage feature is a mess - because of the way the tables are written whether something is a percentage or not is difficult to set (e.g. when you use mean and sd showing the mean/value column as a percentage is not possible) this is because its set at a global level for the table.

As a consequence, the course of action for these tables is to only display numeric values in this instance. 

Time invariant values are also listed as binary features in every case even though this is only true for some of the features. Removing the percentage in this view also acts as a work around for this issue.

I plan to re-write all tables in the app to allow individual level value setting rather than the current approach of having common views for everything. This restructure will be in a future version though. Until then, I will just make sure the values are displayed correctly.
