### ISSUE TITLE
Object 'temporalAnalysisRef' not found when launching Diagnostics Explorer

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/CohortDiagnostics#987]
In CohortDiagnostics v3.0.2, running CD with only inclusion statistics and incidenceRate, getting the following error when launching the DiagnosticsExplorer:
![image](https://user-images.githubusercontent.com/17825660/197993075-c587f350-1f08-4f3e-9a62-4b1f5bddfa74.png)

Caused by the object here not existing:
https://github.com/OHDSI/CohortDiagnostics/blob/befe0eb0e488fa8a4d308fed861cb03c64b67294/inst/shiny/DiagnosticsExplorer/server.R#L2616

**Comment by azimov** [comment]
Hi @MaximMoinat, this bug is because of some hard coding in the cohort diagnostics app that requires a temporal analysis ref file to be present on start up.

This should be fixed in the develop branch of the project. Results from version 3.0.x should still be compatible with the development release.

However, if you want a workaround, inserting some dummy values into the`temporal_analysis_ref` table of the merged results file should let the app load up without error.

**Comment by MaximMoinat** [comment]
Thanks @azimov for both the fix and the workaround. I will check it out.

For now I made the shiny app work by simply running all analyses.

**Comment by azimov** [comment]
Fixed in develop branch
